# Generated by Django 4.0.4 on 2022-08-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeSellClothesApp', '0002_item_ordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_adress',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
