# Generated by Django 4.0.4 on 2022-08-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeSellClothesApp', '0003_item_image_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Out wear')], max_length=2, null=True),
        ),
    ]
