# Generated by Django 4.0.4 on 2022-08-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeSellClothesApp', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'danger'), ('B', 'primary')], max_length=1, null=True),
        ),
    ]
